### ISSUE TITLE
Model paths randomly set 

### ISSUE THREAD

**Issue by HyperUpscale** [mit-han-lab/streaming-llm#31]
If you run initially it download the models on a random folders. For example

C:\Users\super\.cache\huggingface\hub\models--lmsys--vicuna-13b-v1.3\snapshots\6566e9cb1787585d1147dcf4f9bc48f29e1328d2

How is it expected to work the code afterwards?

Loading model from lmsys/vicuna-13b-v1.3 ...
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "examples/run_streaming_llama.py", line 122, in <module>
    main(args)
  File "examples/run_streaming_llama.py", line 80, in main
    model, tokenizer = load(model_name_or_path)
  File "d:\trial\streaming-llm\streaming_llm\utils.py", line 58, in load
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\super\anaconda3\envs\streaming\lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\super\anaconda3\envs\streaming\lib\site-packages\transformers\modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\super\anaconda3\envs\streaming\lib\site-packages\transformers\modeling_utils.py", line 3296, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

**Comment by Guangxuan-Xiao** [comment]
This article has a pretty good explanation on how to fix that issue.

https://huggingface.co/blog/accelerate-large-models
